### ISSUE TITLE
Implement the decorator pattern to check doctor availability

### ISSUE THREAD

**Issue by ViniciusRodrigues10** [ViniciusRodrigues10/medical-scheduling#3]
## Description

Create a decorator to check doctor availability before booking an appointment.

### Task:

- [x] Create the **decorators** folder.
- [ ]  Create **views_decorator.py** file
- [ ] Create a decorator to check doctor availability.
- [ ] Apply the decorator to the appointment booking view..
